pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                
              /*  mvn archetype:generate -DgroupId=io.stockgeeks \
                       -DartifactId=webproject-example \
                       -DarchetypeArtifactId=maven-archetype-webapp */
                
             /*   mvn archetype:generate -DgroupId=io.stockgeeks \
                       -DartifactId=my-app \
                       -DarchetypeArtifactId=maven-archetype-my-app */
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
                
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                 echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
            }
        }
    }
    
    post {
        always {
             //archiveArtifacts artifacts: 'target/*.jar', fingerprint: true, onlyIfSuccessful: true

            archiveArtifacts artifacts: 'artifact.txt', onlyIfSuccessful: true
                }
    }
}
